const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const context = {};
vm.createContext(context);
vm.runInContext(fs.readFileSync(`${__dirname}/../src/camera-controls.js`, 'utf8'), context);
const { move, commandForKey } = context.VestraCameraControls;
const identity = [0, 0, 0, 1];
const close = (actual, expected) => actual.forEach((value, index) => assert.ok(Math.abs(value - expected[index]) < 1e-9, `${actual} != ${expected}`));
close(move([0,0,0], identity, 10, 'forward'), [0,0,-.6]);
close(move([0,0,0], identity, 10, 'backward'), [0,0,.6]);
close(move([0,0,0], identity, 10, 'left'), [-.6,0,0]);
close(move([0,0,0], identity, 10, 'right'), [.6,0,0]);
close(move([0,0,0], identity, 10, 'up'), [0,.6,0]);
close(move([0,0,0], identity, 10, 'down'), [0,-.6,0]);
const yaw90 = [0, Math.SQRT1_2, 0, Math.SQRT1_2];
close(move([0,0,0], yaw90, 10, 'forward'), [-.6,0,0]);
assert.equal(commandForKey('ArrowUp'), 'forward'); assert.equal(commandForKey('E'), 'up'); assert.equal(commandForKey('d'), 'down'); assert.equal(commandForKey('x'), null);
console.log('camera controls: all matrix and key mapping checks passed');
