const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const context = {};
vm.createContext(context);
vm.runInContext(fs.readFileSync(`${__dirname}/../src/camera-controls.js`, 'utf8'), context);
const controls = context.VestraCameraControls;
const { move, commandForKey, lookOrientation } = controls;
const identity = [0, 0, 0, 1];
const close = (actual, expected) => actual.forEach((value, index) => assert.ok(Math.abs(value - expected[index]) < 1e-9, `${actual} != ${expected}`));
close(move([0,0,0], identity, 10, 'forward'), [0,0,-.6]);
close(move([0,0,0], identity, 10, 'backward'), [0,0,.6]);
close(move([0,0,0], identity, 10, 'left'), [-.6,0,0]);
close(move([0,0,0], identity, 10, 'right'), [.6,0,0]);
const yaw90 = [0, Math.SQRT1_2, 0, Math.SQRT1_2];
close(move([0,0,0], yaw90, 10, 'forward'), [-.6,0,0]);
close(move([0,0,0], yaw90, 10, 'right'), [0,0,-.6]);
close(controls.cameraToViewer([2, 3, 4]), [2, -3, -4]);
close(controls.cameraToViewer([0, 1, 0]), [0, -1, 0]);
close(controls.cameraToViewer([0, 0, 1]), [0, 0, -1]);
const matched = controls.cameraBasis(controls.orientationFromBasis([0,0,1], [0,1,0], [-1,0,0]));
close(matched.right, [0,0,1]); close(matched.up, [0,1,0]); close(matched.backward, [-1,0,0]);
let orientation = identity;
for (let index = 0; index < 10_000; index++) orientation = controls.orbit(orientation, .013, -.009);
assert.ok(Math.abs(Math.hypot(...orientation) - 1) < 1e-12, 'orbit quaternion remains unit length');
for (const vector of Object.values(controls.cameraBasis(orientation))) assert.ok(vector.every(Number.isFinite), 'orbit never produces an invalid camera axis');
const lookingRight = lookOrientation(Math.PI / 2, 0);
close(move([0,0,0], lookingRight, 10, 'forward'), [-.6,0,0]);
close(move([0,0,0], lookingRight, 10, 'left'), [0,0,.6]);
// First-person navigation rotates only the orientation. The eye position is
// deliberately independent of yaw/pitch, preventing an orbit around a point
// behind the camera.
const eye = [7, -2, 11];
const rotated = lookOrientation(-2.7, .8);
close(eye, [7, -2, 11]);
assert.notDeepEqual(controls.cameraBasis(identity).forward, controls.cameraBasis(rotated).forward);
const transform = (matrix, point) => [0,1,2].map(row => matrix[row] * point[0] + matrix[4 + row] * point[1] + matrix[8 + row] * point[2] + matrix[12 + row]);
close(transform(controls.viewMatrix(eye, rotated), eye), [0,0,0]);
const forwardPoint = eye.map((value, axis) => value + controls.cameraBasis(rotated).forward[axis] * 5);
close(transform(controls.viewMatrix(eye, rotated), forwardPoint), [0,0,-5]);
const almostVertical = lookOrientation(17 * Math.PI, Math.PI);
assert.ok(Math.abs(Math.hypot(...almostVertical) - 1) < 1e-12, 'look controller remains normalized after unlimited yaw');
assert.ok(Math.abs(controls.cameraBasis(almostVertical).forward[1]) < 1, 'pitch clamp prevents an upside-down camera singularity');
assert.equal(commandForKey('ArrowUp'), 'forward'); assert.equal(commandForKey('W'), 'lookUp'); assert.equal(commandForKey('a'), 'lookLeft'); assert.equal(commandForKey('D'), 'lookRight'); assert.equal(commandForKey('E'), null); assert.equal(commandForKey('x'), null);
console.log('camera controls: all matrix and key mapping checks passed');
